- hosts: FRONT_NIC_IP BACK_NIC_IP
  remote_user: root
  tasks:
  - name: Stop apt-daily.* systemd services
    service:
      name: "{{ item }}"
      state: stopped
    with_items:
      - unattended-upgrades
      - apt-daily
      - apt-daily.timer
      - apt-daily-upgrade
      - apt-daily-upgrade.timer
  - name: Wait for automatic system updates
    become: true
    shell: while sudo fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 1; done;
    with_items:
      - lock
      # - lock-frontend
  - name: update apt cache manual
    shell: apt update
    args:
      executable: /bin/bash
  - name: update apt cache
    apt:
      update_cache: yes
  - name: ensure nginx is at the latest version
    apt:
      name: nginx
      state: latest
    notify:
    - restart nginx
  - name: execute init.bash
    ansible.builtin.shell: |
      indexhtml=/var/www/html/index.nginx-debian.html

      # wait for the cloud-init boot process to complete
      until [ -f /$indexhtml ]; do
        date
        sleep 11
      done

      # initial value
      cat > $indexhtml <<EOF
      INIT
      EOF

      # Internet is availble then more software can be installed if isolated only the software
      # from the ibm mirrors can be installed
      if curl -o /tmp/x https://www.python.org/downloads/release/python-373/; then
        cat > $indexhtml <<EOF
      INTERNET
      EOF
      else
        cat > $indexhtml <<EOF
      ISOLATED
      EOF
      fi
  - name: execute uploaded.sh
    ansible.builtin.script: uploaded.sh
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
