# empty
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: build
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
  triggers:
  - binding:
      name: pipeline-build
    template:
      name: tt-common
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pipeline-build
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: namespace
    value: getting-started
  - name: gitrepositoryurl
    value: "https://github.com/$(body.repository.full_name)"
  - name: script
    value: ./scripts/pipeline-BUILD.sh
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: tt-common
spec:
  params:
  - name: script
  
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: pipelinerun-$(uid)
    spec:
      pipelineRef:
        name: pipeline-input-parameter-variable
      workspaces:
      - name: pipeline-workspace
        emptyDir: {}
      params:
      - name: gitrepositoryurl
        value: $(params.gitrepositoryurl)
      - name: script
        value: $(params.script)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-input-parameter-variable
spec:
  workspaces:
  - name: pipeline-workspace
  params:
  - name: script
  - name: gitrepositoryurl
  tasks:
  - name: script
    when:
    - input: "$(params.gitrepositoryurl)"
      operator: notin
      values: [ "testing" ]
    workspaces:
    - name: task-workspace
      workspace: pipeline-workspace
    params:
    - name: script
      value: $(params.script)
    - name: gitrepositoryurl
      value: $(params.gitrepositoryurl)
    taskRef:
      name: gasket
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gasket
spec:
  workspaces:
  - name: task-workspace 
    mountPath: /working   
  params:
  - name: script
  - name: gitrepositoryurl
  steps:
  - name: execute-script
    image: ibmcom/pipeline-base-image:2.9
    envFrom:
    - configMapRef:
        name: environment-properties
    - secretRef:
        name: secure-properties     
    env:
    - name: script
      value: $(params.script)
    command: ["/bin/bash", "-c"]
    args:
    - |
      env
