# empty
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: build
spec:
  triggers:
  - binding:
      name: pipeline-BUILD
    template:
      name: tt-common
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pipeline-BUILD
spec:
  params:
  - name: script
    value: ./scripts/pipeline-BUILD.sh
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: tt-common
spec:
  params:
  - name: script
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: pipelinerun-$(uid)
    spec:
      pipelineRef:
        name: pipeline-input-parameter-variable
      workspaces:
      - name: pipeline-workspace
        emptyDir: {}
      params:
      - name: script
        value: $(params.script)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-input-parameter-variable
spec:
  workspaces:
  - name: pipeline-workspace
  params:
  - name: script
  tasks:
  - name: script
    workspaces:
    - name: task-workspace
      workspace: pipeline-workspace
    params:
    - name: script
      value: $(params.script)
    taskRef:
      name: gasket
