# empty
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: build
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
  triggers:
  - binding:
      name: pipeline-build
    template:
      name: tt-common
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pipeline-build
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: namespace
    value: getting-started
  - name: gitrepositoryurl
    value: "https://github.com/$(body.repository.full_name)"
  - name: script
    value: ./scripts/pipeline-BUILD.sh
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: tt-common
spec:
  params:
  - name: script
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: pipelinerun-$(uid)
    spec:
      pipelineRef:
        name: pipeline-input-parameter-variable
      workspaces:
      - name: pipeline-workspace
        emptyDir: {}
      params:
      - name: script
        value: $(params.script)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-input-parameter-variable
spec:
  workspaces:
  - name: pipeline-workspace
  params:
  - name: script
  tasks:
  - name: script
    workspaces:
    - name: task-workspace
      workspace: pipeline-workspace
    params:
    - name: script
      value: $(params.script)
    taskRef:
      name: gasket
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gasket
spec:
  workspaces:
  - name: task-workspace 
    mountPath: /working   
  params:
  - name: script
  steps:
  - name: execute-script
    image: ibmcom/pipeline-base-image:2.9
    envFrom:
    - configMapRef:
        name: environment-properties
    - secretRef:
        name: secure-properties     
    env:
    - name: script
      value: $(params.script)
    command: ["/bin/bash", "-c"]
    args:
    - |
      env

      # verify all the required variables are set
      set -u
      for e in GIT_REPO GIT_BRANCH REGISTRY_REGION_ID REGISTRY_NAMESPACE  IMAGE_NAME TARGET_REGION_ID TARGET_NAMESPACE TARGET_RESOURCE_GROUP COS_PLAN APP_ID_PLAN CLOUDANT_PLAN script; do
        eval "echo $e="'$'$e
      done
      set +u
      cd /working
      # Builder type: Container Registry, initializes this default
      export ARCHIVE_DIR=.
      # Builder type: Kubernetes expects the ibmcloud cli to be connected to the cluster and the
      # environment exported below.  The ibmcloud cli region could be initialized to the toolchain
      # region instead of the kubernets cluster region
      if [ -z $GIT_BRANCH ]; then
        git clone -q $GIT_REPO .
      else
        git clone -q -b $GIT_BRANCH $GIT_REPO .
      fi
      cd testing-the-test
      git log --format= -n 1 --name-only