# Pipeline
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-input-parameter-variable
spec:
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: script
      workspaces:
        - name: task-workspace
          workspace: pipeline-workspace
      params:
        - name: toolchain-dir
          value: ".tekton"
        - name: app-dir
          value: "one"
      taskRef:
        name: detect-change-task
    - name: test-output
      when: 
      - input: "$(tasks.script.results.is_toolchain)"
        operator: in
        values: ["true"]
      workspaces:
        - name: task-workspace
          workspace: pipeline-workspace
      params:
        - name: mystring
          value: "Hello toolchain"
      taskRef:
        name: print-changed-paths
    - name: test-output2
      when: 
      - input: "$(tasks.script.results.is_toolchain)"
        operator: in
        values: ["true"]
      workspaces:
        - name: task-workspace
          workspace: pipeline-workspace
      params:
        - name: mystring
          value: "Hello app"
      taskRef:
        name: print-changed-paths
