# Pipeline
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-input-parameter-variable
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: script
  tasks:
    - name: script
      workspaces:
        - name: task-workspace
          workspace: pipeline-workspace
      params:
        - name: toolchain-dir
          value: ".tekton"
      taskRef:
        name: detect-change-task
    - name: test-output
      when: 
      - input: "$(tasks.script.results.is_toolchain)"
        operator: in
        values: ["true"]
      workspaces:
        - name: task-workspace
          workspace: pipeline-workspace
      params:
        - name: changeddirectories
          value: "$(tasks.script.results.changed_directories)"
      taskRef:
        name: print-changed-paths
