# Tasks
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: detect-change-task
spec:
  results:
    - name: changed_directories
      description: list of changed directories
    - name: is_app
      description: changed files belong to app
    - name: is_toolchain
      description: changed files belong to toolchain
  workspaces:
    - name: task-workspace
      mountPath: /working
  params:
    - name: toolchain_dir
  steps:
    - name: execute-script
      image: ibmcom/pipeline-base-image:2.9
      envFrom:
        - configMapRef:
            name: environment-properties
        - secretRef:
            name: secure-properties
      env:
        - name: toolchain_dir
          value: $(params.toolchain_dir)
      command: ["/bin/bash", "-c"]
      args:
        - |
          # verify all the required variables are set
          set -u
          for e in GIT_REPO GIT_BRANCH REGISTRY_REGION_ID REGISTRY_NAMESPACE  IMAGE_NAME TARGET_REGION_ID TARGET_RESOURCE_GROUP COS_PLAN APP_ID_PLAN CLOUDANT_PLAN; do
            eval "echo $e="'$'$e
          done
          set +u
          cd /working
          # Builder type: Container Registry, initializes this default
          export ARCHIVE_DIR=.
          # Builder type: Kubernetes expects the ibmcloud cli to be connected to the cluster and the
          # environment exported below.  The ibmcloud cli region could be initialized to the toolchain
          # region instead of the kubernets cluster region
          if [ -z $GIT_BRANCH ]; then
            git clone -q $GIT_REPO .
          else
            git clone -q -b $GIT_BRANCH $GIT_REPO .
          fi
          changed_directories=$(git log --format= -n 1 --name-only | grep / | awk 'BEGIN {FS="/"} {print $1}' | uniq)
          echo "changed_directories:\n$changed_directories"
          for d in ${changed_directories[@]}; do
           echo $d
          done
          echo $changed_directories | tee $(results.changed_directories.path)
          if [[ " ${changed_directories[@]} " =~ " ${toolchain_dir} " ]]; then
            echo "true" | tee $(results.is_toolchain.path)
          fi
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: print-changed-paths
spec:
  workspaces:
    - name: task-workspace
      mountPath: /working
  params:
  - name: changeddirectories
  steps:
    - name: print-changed-paths
      image: bash:latest
      env:
        - name: changeddirectories
          value: $(params.changeddirectories)
      script: |
        #!/usr/bin/env bash
        env
        echo "This is another step. Changed directories:"
        echo "Directories: $changeddirectories"
        echo "Loop:"
        for d in ${changeddirectories[@]}; do
          echo $d
        done
        which git
