# Tasks
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: detect-change-task
spec:
  results:
    - name: is_app
      description: changed files belong to app
    - name: is_toolchain
      description: changed files belong to toolchain
  workspaces:
    - name: task-workspace
      mountPath: /working
  params:
    - name: toolchain-dir
    - name: app-dir
  steps:
    - name: execute-script
      image: ibmcom/pipeline-base-image:2.9
      envFrom:
        - configMapRef:
            name: environment-properties
        - secretRef:
            name: secure-properties
      env:
        - name: toolchaindirs
          value: $(params.toolchain-dir)
        - name: appdir
          value: $(params.app-dir)
      command: ["/bin/bash", "-c"]
      args:
        - |
          cd /working
          if [ -z $GIT_BRANCH ]; then
            git clone -q $GIT_REPO .
          else
            git clone -q -b $GIT_BRANCH $GIT_REPO .
          fi
          changed_directories=$(git log --format= -n 1 --name-only | grep / | awk 'BEGIN {FS="/"} {print $1}' | uniq)
          echo "changed_directories:\n$changed_directories"
          printf false | tee $(results.is_toolchain.path)
          for d in ${toolchaindirs[@]}; do
            if [[ " ${changed_directories[@]} " =~ "${d}" ]]; then
              printf true | tee $(results.is_toolchain.path)
              break
            fi
          done
          if [[ " ${changed_directories[@]} " =~ "${appdir}" ]]; then
            printf true | tee $(results.is_app.path)
          else
            printf false | tee $(results.is_app.path)
          fi

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: print-changed-paths
spec:
  workspaces:
    - name: task-workspace
      mountPath: /working
  params:
    - name: mystring
  steps:
    - name: print-changed-paths
      image: bash:latest
      env:
        - name: mystring
          value: $(params.mystring)
      script: |
        #!/usr/bin/env bash
        env
        echo "mystring=$mystring"