# Tasks
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: detect-change-task
spec:
  results:
    - name: is_app
      description: changed files belong to app
    - name: is_toolchain
      description: changed files belong to toolchain
  workspaces:
    - name: task-workspace
      mountPath: /working
  params:
    - name: toolchain-dir
  steps:
    - name: execute-script
      image: ibmcom/pipeline-base-image:2.9
      envFrom:
        - configMapRef:
            name: environment-properties
        - secretRef:
            name: secure-properties
      env:
        - name: toolchaindir
          value: $(params.toolchain-dir)
      command: ["/bin/bash", "-c"]
      args:
        - |
          # verify all the required variables are set
          set -u
          for e in GIT_REPO GIT_BRANCH REGISTRY_REGION_ID REGISTRY_NAMESPACE  IMAGE_NAME TARGET_REGION_ID TARGET_RESOURCE_GROUP COS_PLAN APP_ID_PLAN CLOUDANT_PLAN; do
            eval "echo $e="'$'$e
          done
          set +u
          cd /working
          # Builder type: Container Registry, initializes this default
          export ARCHIVE_DIR=.
          # Builder type: Kubernetes expects the ibmcloud cli to be connected to the cluster and the
          # environment exported below.  The ibmcloud cli region could be initialized to the toolchain
          # region instead of the kubernets cluster region
          if [ -z $GIT_BRANCH ]; then
            git clone -q $GIT_REPO .
          else
            git clone -q -b $GIT_BRANCH $GIT_REPO .
          fi
          changed_directories=$(git log --format= -n 1 --name-only | grep / | awk 'BEGIN {FS="/"} {print $1}' | uniq)
          echo "changed_directories:\n$changed_directories"
          if [[ " ${changed_directories[@]} " =~ " ${toolchaindir} " ]]; then
            printf true | tee $(results.is_toolchain.path)
          else
            printf false | tee $(results.is_toolchain.path)
          fi
          if [[ " ${changed_directories[@]} " =~ " ${appdir} " ]]; then
            printf true | tee $(results.is_app.path)
          else
            printf false | tee $(results.is_app.path)
          fi

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: print-changed-paths
spec:
  workspaces:
    - name: task-workspace
      mountPath: /working
  params:
    - name: mystring
  steps:
    - name: print-changed-paths
      image: bash:latest
      env:
        - name: mystring
          value: $(params.mystring)
      script: |
        #!/usr/bin/env bash
        env
        echo "mystring=$mystring"